ComputerStore/Controllers/ProductListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab5.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
namespace Lab5.Controllers
{
    public class ProductListController : Controller
    {
        private readonly ProductContext _context;
        public ProductListController(ProductContext context)
        {
            _context = context;
        }
        // GET: Products
        [Authorize]
        public async Task<IActionResult> Index(int? categoryId)
        {
            ViewBag.Title = "Продукти";
            IQueryable<Product> products =
            _context.Products.Include(p => p.Category);
            if (categoryId.HasValue && categoryId > 0)
            {
                products = products.Where(p => p.CategoryID == categoryId);
            }
            return View((await products.ToListAsync())
            .OrderByDescending(x => x.CategoryID));
        }
        [Authorize]
        public async Task<IActionResult> Details(int? productID)
        {
            if (productID == null)
            {
                return NotFound();
            }
            var product = await _context.Products
            .Include(p => p.Category)
            .AsNoTracking()
            .FirstOrDefaultAsync(m => m.ProductID == productID);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
    }
}

ComputerStore/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/content/Lab.css" rel="stylesheet" />
    <title>@ViewBag.Title - Tech Kingdom</title>
</head>
<body>
    <div class="container">
        <header>
            <aside><img src="~/images/img02.png" style="height:71px;width:100px;float: left;border: 1px solid #00046c;margin-top:1px;margin-right:20px;" /><p>Tech Kingdom</p></aside>
            <nav>
                <ul>
                    <li>
                        <a asp-controller="Home" asp-action="Index">Начало</a>
                    </li>
                    <li>
                        <a asp-controller="Home" asp-action="ForUs">За нас</a>
                    </li>
                    <li>
                        <a asp-controller="Home" asp-action="Contacts">Контакти</a>
                    </li>
                    <li>
                        <a asp-controller="Home" asp-action="Orders">Поръчки</a>
                    </li>
                    <li>
                        <a asp-controller="ProductList" asp-action="Index">Продукти</a>
                    </li>
                    <partial name="_LoginPartial" />
                </ul>
            </nav>
        </header> @RenderBody() <footer><p>&copy; @DateTime.Now.Year - Tech Kingdom</p></footer>
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>